// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace SimplerWater.Water.Effects
{
    public static partial class MaterialWaterSurfaceEmissiveShadingKeys
    {
        public static readonly ObjectParameterKey<Texture> CausticsTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<float> CausticsSpeed = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<float> CausticsScale = ParameterKeys.NewValue<float>(8);
        public static readonly ValueParameterKey<float> CausticsStrength = ParameterKeys.NewValue<float>(1);
        public static readonly ValueParameterKey<float> CausticsSplit = ParameterKeys.NewValue<float>(0.0015f);
        public static readonly ValueParameterKey<float> FogDensity = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<Color3> FogColor = ParameterKeys.NewValue<Color3>(new Color3(0,0,0));
        public static readonly ValueParameterKey<float> RefractionStrength = ParameterKeys.NewValue<float>(25);
        public static readonly ValueParameterKey<Color3> TintColor = ParameterKeys.NewValue<Color3>(new Color3(0.6f,0.63f,0.79f));
        public static readonly ValueParameterKey<float> FresenlOffset = ParameterKeys.NewValue<float>(0.05f);
        public static readonly ValueParameterKey<float> FresnelStrength = ParameterKeys.NewValue<float>(0.55f);
        public static readonly ValueParameterKey<float> FresnelPower = ParameterKeys.NewValue<float>(14);
    }
}
